FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN apt-get update && pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt 

EXPOSE 8000

CMD [CMD ["uvicorn", "main_api:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]]